// <auto-generated />
using System;
using ClinicalEpilepsyApp.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClinicalEpilepsyApp.Infrastructure.Migrations
{
    [DbContext(typeof(ClinicalEpilepsyAppDbContext))]
    [Migration("20240425130738_UpdateModels")]
    partial class UpdateModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClinicalEpilepsyApp.Domain.DBModels.EcgAlarm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AlarmTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("CSI100")
                        .HasColumnType("int");

                    b.Property<int>("CSI30")
                        .HasColumnType("int");

                    b.Property<int>("CSI50")
                        .HasColumnType("int");

                    b.Property<Guid>("EcgProcessedMeasurementProcessedMeasurementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ModCSI100")
                        .HasColumnType("int");

                    b.Property<int>("ModCSI30")
                        .HasColumnType("int");

                    b.Property<int>("ModCSI50")
                        .HasColumnType("int");

                    b.Property<int>("PatientCSIThreshold")
                        .HasColumnType("int");

                    b.Property<string>("PatientId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PatientModCSIThreshold")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EcgProcessedMeasurementProcessedMeasurementId");

                    b.HasIndex("PatientId");

                    b.ToTable("EcgAlarms");
                });

            modelBuilder.Entity("ClinicalEpilepsyApp.Domain.DBModels.EcgProcessedMeasurement", b =>
                {
                    b.Property<Guid>("ProcessedMeasurementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PatientId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProcessedEcgChannel1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcessedEcgChannel2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcessedEcgChannel3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProcessedMeasurementId");

                    b.HasIndex("PatientId");

                    b.ToTable("EcgProcessedMeasurements");
                });

            modelBuilder.Entity("ClinicalEpilepsyApp.Domain.DBModels.Patient", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CSI")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("ClinicalEpilepsyApp.Domain.DBModels.EcgAlarm", b =>
                {
                    b.HasOne("ClinicalEpilepsyApp.Domain.DBModels.EcgProcessedMeasurement", "EcgProcessedMeasurement")
                        .WithMany()
                        .HasForeignKey("EcgProcessedMeasurementProcessedMeasurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicalEpilepsyApp.Domain.DBModels.Patient", "Patient")
                        .WithMany("EcgAlarms")
                        .HasForeignKey("PatientId");

                    b.Navigation("EcgProcessedMeasurement");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ClinicalEpilepsyApp.Domain.DBModels.EcgProcessedMeasurement", b =>
                {
                    b.HasOne("ClinicalEpilepsyApp.Domain.DBModels.Patient", "Patient")
                        .WithMany("EcgProcessedMeasurements")
                        .HasForeignKey("PatientId");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ClinicalEpilepsyApp.Domain.DBModels.Patient", b =>
                {
                    b.Navigation("EcgAlarms");

                    b.Navigation("EcgProcessedMeasurements");
                });
#pragma warning restore 612, 618
        }
    }
}
